// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    on_db_failure: 'exit',
    watcher_update_interval: 10,
    robot_disallow_urls: ['/delete', '/edit'],
    image_width_scale: 300,
    default_topic: 'Random'
  };

}).call(this);
