// Generated by CoffeeScript 1.10.0
(function() {
  var activitySchema, mongoose;

  mongoose = require("mongoose");

  activitySchema = new mongoose.Schema({
    topic: String,
    action: String,
    detail: String,
    bitId: mongoose.Schema.Types.ObjectId,
    date: {
      type: Date,
      "default": Date.now
    }
  });

  module.exports = mongoose.model('Activity', activitySchema);

}).call(this);
